name: Build Electron App

on:
  push:
    branches:
      - main  # Déclencher le workflow lorsqu'il y a un push sur la branche "main"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.18.1]
    steps:
        - name: Clean up node_modules (Windows)
            if: runner.os == 'Windows'
            run: |
                Remove-Item -Recurse -Force ./node_modules
                rmdir /s /q node_modules
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build

      - name: Package Electron App
        run: |
          npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux' }} --publish never

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ matrix.os }}
          path: dist/